-- AlterTable
ALTER TABLE "User" ADD COLUMN     "caloriesGoal" DOUBLE PRECISION NOT NULL DEFAULT 2000,
ADD COLUMN     "carbsGoal" DOUBLE PRECISION NOT NULL DEFAULT 200,
ADD COLUMN     "fatGoal" DOUBLE PRECISION NOT NULL DEFAULT 65,
ADD COLUMN     "proteinGoal" DOUBLE PRECISION NOT NULL DEFAULT 150;
